### ISSUE TITLE
truncated plot legend 

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/SciQLop#30]
<img width="194" alt="image" src="https://github.com/SciQLop/SciQLop/assets/3200931/bd6bb917-081f-439b-a0f0-6aecb94ecd45">

Depending on the monitor size and number of plot in the panel, the legend could be truncated as on the above capture.
Two solutions maybe:

- change layout from lines to columns (see matplotlib), or "best" if possible
- allow the legend to be collapsed and scrolled (not great)...

**Comment by jeandet** [comment]
Option 1 is possible, but there won't be any great solution here since the main issue is the lack of space. I would argue that in such cases, you might also want to be able to just hide the legend (on demand).
The legend is a grid layout, I think I can automatically increase column count when the legend is cropped. I'll also add options in the settings panel.

**Comment by nicolasaunai** [comment]
another way to see this issue is maybe also to enable the manual vertical resizing of plots inside a panel?

**Comment by jeandet** [comment]
> another way to see this issue is maybe also to enable the manual vertical resizing of plots inside a panel?

This implemented and just pushed in main.
