### ISSUE TITLE
Main app window resized automatically

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/SciQLop#33]
* SciQLop version: c356ca3  (but has appeared since a long time ago)
* Python version: 3.10
* Operating System: Mac OS 13.3

### Description

When not in full screen:
The main application window is often resized so that the bottom appears hidden behind the dock.
There is perhaps a way to stop it where the dock is.

**Comment by jeandet** [comment]
It turns out that the embedded web browser was always asking for more space. From now there should be now resize unless there is no choice. The expected behavior is that Qt try its best to give at least the minimum required size for widgets to be drawn, so widgets should not requests for much more than necessary.
